# @package _global_
model:
  beta_end: 0.02
  beta_schedule: linear
  beta_start: 0.0001
  hidden_dim: 64
  latent_dim: 8
  n_fourier: 30
  n_layers: 3
  num_diffusion_timesteps: 30
train:
  bsize: 256
  check_val_every_n_epoch: 5
  loss_weight: 1.0
  lr_inloop: 0.1
  lr_outloop: 0.001
  lr_patience: 30
  max_epochs: 500
  name_exp: zinc250k
  num_inner_steps: 3
  offline: false
  patience: 100
  proj: exp
  measure_on: val/VUN
  reg_z: true
  seed: 2017
